apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: resync
spec:
  params:
    - description: The component id
      name: COMPONENT_ID
      type: string
  steps:
    - args:
        - >-
          echo "Performing an oc delete pod to automatically reload the new image" && oc delete pod -n $(params.COMPONENT_ID)-{{ .Values.lab.username }} -l
          app.kubernetes.io/instance={{ .Values.lab.username }}-$(params.COMPONENT_ID)-manifests  && echo "" && echo "CTF -- Hey hey... nice to perform an oc with the pipeline service account; can we do more; like oc get apps ?" && echo "" && oc get app {{ .Values.lab.username }}-env-manifests -n openshift-gitops -o jsonpath='{.metadata.annotations}'
      command:
        - /bin/bash
        - '-c'
      image: 'quay.io/openshift/origin-cli:latest'
      name: resync
      resources: {}
